Repository ProjectEvergreen/greenwood, pull requests merged in 2019-10, with the labels that each got.

#217 Fixing Errors With Consistent Unit Tests
  package.json
  packages/cli/package.json
  packages/cli/src/config/webpack.config.common.js
  packages/cli/src/index.js
  packages/cli/src/lib/browser.js
  packages/cli/src/lib/renderer.js
  packages/cli/src/lifecycles/compile.js
  packages/cli/src/lifecycles/config.js
  packages/cli/src/lifecycles/context.js
  packages/cli/src/lifecycles/graph.js
  packages/cli/src/lifecycles/scaffold.js
  packages/cli/src/lifecycles/serialize.js
  packages/cli/src/templates/index.html
  packages/cli/test/cases/build.config.default/build.config.default.spec.js
  packages/cli/test/cases/build.config.error-public-path/build.config.error-public-path.spec.js
  packages/cli/test/cases/build.config.error-theme-file/build.config.error-theme-file.spec.js
  packages/cli/test/cases/build.config.error-title/build.config.error-title.spec.js
  packages/cli/test/cases/build.config.error-workspace-absolute/build.config.error-workspace-absolute.spec.js
  packages/cli/test/cases/build.config.error-workspace/build.config.error-workspace.spec.js
  packages/cli/test/cases/build.config.meta/build.config.meta.spec.js
  packages/cli/test/cases/build.config.public-path/build.config.public-path.spec.js
  packages/cli/test/cases/build.config.theme/build.config.theme.spec.js
  packages/cli/test/cases/build.config.title/build.config.title.spec.js
  packages/cli/test/cases/build.config.workspace-custom/build.config.workspace-custom.spec.js
  packages/cli/test/cases/build.default.workspace-assets/build.default.workspace-assets.spec.js
  packages/cli/test/cases/build.default.workspace-getting-started/build.default.workspace-getting-started.spec.js
  packages/cli/test/cases/build.default.workspace-nested/build.default.workspace-nested.spec.js
  packages/cli/test/cases/build.default.workspace-template-app/build.default.workspace-template-app.spec.js
  packages/cli/test/cases/build.default.workspace-template-page-style/build.default.workspace-template-page-style.spec.js
  packages/cli/test/cases/build.default.workspace-template-page/build.default.workspace-template-page.spec.js
  packages/cli/test/cases/build.default/build.default.spec.js
  packages/cli/test/cases/build.plugins-error-provider/build.plugins-error-provider.spec.js
  packages/cli/test/cases/build.plugins-error-type/build.plugins-error-type.spec.js
  packages/cli/test/cases/build.plugins-index/build.plugins-index.spec.js
  packages/cli/test/cases/build.plugins-webpack/build-plugins-webpack.spec.js
  packages/plugin-google-analytics/test/cases/default/default.spec.js
  packages/plugin-google-analytics/test/cases/error-analytics-id/error-analytics-id.spec.js
  packages/plugin-google-analytics/test/cases/option-anonymous/option-anonymous.spec.js
  packages/plugin-polyfills/test/cases/default/default.spec.js
  test/smoke-test.js
  test/test-bed.js
Labels: P0, bug, enhancement

#221 Bug/issue 220 puppeteer external requests
  packages/cli/src/lib/renderer.js
  packages/plugin-google-analytics/test/cases/default/default.spec.js
  test/smoke-test.js
Labels: CLI, P0, bug

#212 Enhancement/issue 9 polyfill using webcomponent loader
  packages/cli/src/lib/renderer.js
  packages/plugin-polyfills/README.md
  packages/plugin-polyfills/package.json
  packages/plugin-polyfills/src/index.js
  packages/plugin-polyfills/test/cases/default/default.spec.js
  test/test-bed.js
  www/assets/web-components-browser-support.png
  www/components/shelf/about.json
  www/pages/about/how-it-works.md
Labels: CLI, documentation, enhancement

#223 Website/issue 222 Shelf List Items
  www/components/shelf/shelf.js
Labels: technical, website

#243 ISSUE #124 - refactor chevron svgs by removing them from the shelf component into…
  www/components/icons/chevron-down/chevron-down.js
  www/components/icons/chevron-right/chevron-right.js
  www/components/shelf/shelf.js
Labels: website

#239 resolve website issue 143, remove index dependence for the shelf rend…
  www/components/shelf/about.json
  www/components/shelf/documentation-list.json
  www/components/shelf/getting-started-list.json
  www/components/shelf/plugins.json
  www/components/shelf/shelf.js
Labels: website

#242 update to migrated getting started repo path
  README.md
  packages/cli/test/cases/build.default.workspace-getting-started/build.default.workspace-getting-started.spec.js
  www/pages/getting-started/branding.md
  www/pages/getting-started/creating-content.md
  www/pages/getting-started/next-steps.md
  www/pages/getting-started/quick-start.md
Labels: technical

#247 website bug/issue 244 sub-nav expand/collapse
  www/components/shelf/shelf.js
Labels: question, website

#246 fix erros in handleHashChange() and add page load listener to scroll component
  www/components/scroll/scroll.js
Labels: question, website

#249 add social links with icon componet to header
  www/components/header/header.css
  www/components/header/header.js
  www/components/icons/github-icon.js
  www/components/icons/slack-icon.js
  www/components/icons/twitter-icon.js
  www/components/social-icons/social-icons.css
  www/components/social-icons/social-icons.js
Labels: question, website

#248 keywords for packages
  packages/cli/package.json
  packages/plugin-google-analytics/package.json
  packages/plugin-polyfills/package.json
Labels: technical

#237 Remove Peer Dependency Warnings For Greenwood Plugins
  packages/plugin-google-analytics/package.json
  packages/plugin-polyfills/package.json
Labels: CLI, Plugins, question, technical
