Repository ProjectEvergreen/greenwood, pull requests merged in 2019-08, with the labels that each got.

#158 SEO and Accessability fixes
  www/components/card/card.js
  www/components/header/header.js
  www/pages/index.md
Labels: website

#159 netlify status badge
  README.md
Labels: 0.3.4

#161 fix and clarify template creation
  www/pages/docs/layouts.md
  www/pages/getting-started/creating-content.md
Labels: 0.3.4, website

#164 Website fixing banner and header jump on load
  www/components/banner/banner.css
  www/components/header/header.css
  www/components/header/header.js
Labels: website

#163 getting started guide feedback
  README.md
  www/assets/getting-started-netlify-config.png
  www/assets/greenwood-netlify-config.png
  www/pages/docs/index.md
  www/pages/getting-started/build-and-deploy.md
  www/pages/getting-started/creating-content.md
  www/pages/getting-started/key-concepts.md
  www/pages/index.md
Labels: website

#166 readability and formatting enhancement to creating content section
  www/components/shelf/getting-started-list.json
  www/pages/about/community.md
  www/pages/about/index.md
  www/pages/getting-started/branding.md
  www/pages/getting-started/build-and-deploy.md
  www/pages/getting-started/creating-content.md
Labels: website

#165 delete file cli theme.css file
  packages/cli/templates/theme.css
Labels: technical

#168 disable host check for devServer and fix host parsing
  packages/cli/config/webpack.config.develop.js
  packages/cli/lifecycles/config.js
  test/cli/test-bed.js
  www/pages/docs/configuration.md
Labels: P0, bug

#171 Update configuration.md
  www/pages/docs/configuration.md
Labels: website

#173 Update README.md
  README.md
Labels: chore

#177 compress larger images and logo
  www/assets/getting-started-netlify-config.png
  www/assets/greenwood-logo.png
Labels: website

#174 improve loading performance / minification for JavaScript polyfills
  packages/cli/templates/index.html
  test/cli/cases/build.config.meta/build.config.meta.spec.js
  test/cli/cases/build.config.public-path/build.config.public-path.spec.js
  test/cli/cases/build.config.title/build.config.title.spec.js
  test/cli/cases/build.default.workspace-template-app/build.default.workspace-template-app.spec.js
  test/cli/smoke-test.js
Labels: bug
