Repository ProjectEvergreen/greenwood, pull requests merged in 2020-06, with the labels that each got.

#338 render keyword not needed for code formatting in markdown (wc-markdown-loader to 0.2.0)
  packages/cli/package.json
  packages/cli/test/cases/build.default.workspace-nested/src/pages/blog/2019/index.md
  www/pages/about/how-it-works.md
  www/pages/docs/component-model.md
  www/pages/docs/configuration.md
  www/pages/docs/css-and-images.md
  www/pages/docs/data.md
  www/pages/docs/front-matter.md
  www/pages/docs/index.md
  www/pages/docs/layouts.md
  www/pages/docs/markdown.md
  www/pages/docs/menus.md
  www/pages/getting-started/branding.md
  www/pages/getting-started/build-and-deploy.md
  www/pages/getting-started/creating-content.md
  www/pages/getting-started/index.md
  www/pages/getting-started/key-concepts.md
  www/pages/getting-started/next-steps.md
  www/pages/getting-started/project-setup.md
  www/pages/getting-started/quick-start.md
  www/pages/guides/cloudflare-workers-deployment.md
  www/pages/guides/firebase.md
  www/pages/guides/netlify-cms.md
  www/pages/guides/s3-cloudfront.md
  www/pages/index.md
  www/pages/plugins/index-hooks.md
  www/pages/plugins/index.md
  www/pages/plugins/webpack.md
  www/styles/page.css
  yarn.lock
Labels: CLI, dependencies, documentation, enhancement

#359 task/issue-358 Fix Getting Started menu indices and content numbered lists
  www/pages/getting-started/branding.md
  www/pages/getting-started/creating-content.md
  www/pages/getting-started/index.md
  www/pages/getting-started/key-concepts.md
  www/pages/getting-started/project-setup.md
Labels: website

#361 task/issue 360 update app-template documentation
  www/pages/docs/layouts.md
Labels: documentation, website

#366 task/issue 365 add support for custom babel/postcss configs in user workspace
  .browserslistrc
  packages/cli/src/config/webpack.config.common.js
  packages/cli/src/lifecycles/context.js
  packages/cli/test/cases/build.config.babel/babel.config.js
  packages/cli/test/cases/build.config.babel/build.config.babel.spec.js
  packages/cli/test/cases/build.config.babel/src/pages/index.md
  packages/cli/test/cases/build.config.postcss/build.config.postcss.spec.js
  packages/cli/test/cases/build.config.postcss/postcss.config.js
  packages/cli/test/cases/build.config.postcss/src/pages/hello.md
  packages/cli/test/cases/build.config.postcss/src/pages/index.md
  postcss.config.js
  www/package.json
  www/pages/docs/build.md
  www/pages/docs/configuration.md
  www/pages/docs/css-and-images.md
  www/pages/docs/data.md
  www/pages/docs/front-matter.md
  www/pages/docs/markdown.md
  www/pages/docs/menus.md
  www/pages/docs/tech-stack.md
  yarn.lock
Labels: documentation, enhancement, website

#368 bug/issue 367 fix google analytics usage
  packages/plugin-google-analytics/README.md
  packages/plugin-google-analytics/src/index.js
  packages/plugin-google-analytics/test/cases/default/default.spec.js
  www/components/header/header.js
  www/components/social-icons/social-icons.js
Labels: Plugins, bug, documentation, website

#374 task/issue 373 add unified preset extensibility through greenwood config
  greenwood.config.js
  packages/cli/package.json
  packages/cli/src/config/webpack.config.common.js
  packages/cli/src/lifecycles/config.js
  packages/cli/test/cases/build.config.markdown-custom.plugins/build.config.markdown-custom.spec.js
  packages/cli/test/cases/build.config.markdown-custom.plugins/greenwood.config.js
  packages/cli/test/cases/build.config.markdown-custom.settings/build.config.markdown-custom.settings.spec.js
  packages/cli/test/cases/build.config.markdown-custom.settings/greenwood.config.js
  packages/cli/test/cases/build.config.markdown-custom.settings/src/pages/index.md
  www/pages/docs/configuration.md
  www/pages/docs/markdown.md
  yarn.lock
Labels: CLI, documentation, enhancement

#376 task/issue 370 support webpack customization
  packages/cli/src/lifecycles/context.js
  packages/cli/src/tasks/build.js
  packages/cli/src/tasks/develop.js
  packages/cli/test/cases/build.default.webpack/build.default.webpack.spec.js
  packages/cli/test/cases/build.default.webpack/webpack.config.common.js
  packages/cli/test/cases/build.default.webpack/webpack.config.develop.js
  packages/cli/test/cases/build.default.webpack/webpack.config.prod.js
  www/pages/docs/build.md
Labels: CLI, documentation, enhancement

#369 task/issue 329 Auto link headings and scroll all headings
  greenwood.config.js
  www/assets/link.png
  www/components/scroll/scroll.js
  www/package.json
  www/styles/page.css
  yarn.lock
Labels: help wanted, website
