Repository ProjectEvergreen/greenwood, pull requests merged in 2020-08, with the labels that each got.

#407 technical/issue 406 add ls-lint for filenames
  .ls-lint.yml
  package.json
  www/assets/fonts/source-sans-pro.css
  www/styles/theme.css
  yarn.lock
Labels: technical

#408 Technical/issue 404 netlify configuration
  netlify.toml
  package.json
  www/pages/guides/netlify-deploy.md
Labels: Guide, technical, website

#396 Rfc/issue 354 strict / SSG mode
  packages/cli/src/data/client.js
  packages/cli/src/data/queries/config.gql
  packages/cli/src/data/schema/config.js
  packages/cli/src/lifecycles/config.js
  packages/cli/src/lifecycles/serialize.js
  packages/cli/test/cases/build.config.error-mode/build.config.error-mode.spec.js
  packages/cli/test/cases/build.config.error-mode/greenwood.config.js
  packages/cli/test/cases/build.config.meta/build.config.meta.spec.js
  packages/cli/test/cases/build.config.mode/build.config.mode.spec.js
  packages/cli/test/cases/build.config.mode/greenwood.config.js
  packages/cli/test/cases/build.config.mode/src/pages/about/index.md
  packages/cli/test/cases/build.config.mode/src/pages/hello.md
  packages/cli/test/cases/build.config.mode/src/pages/index.md
  packages/cli/test/cases/build.config.title/build.config.title.spec.js
  packages/cli/test/cases/build.data.graph-custom-frontmatter/build.data.graph-custom-frontmatter.spec.js
  packages/cli/test/cases/build.data.graph/build.data.graph.spec.js
  packages/cli/test/cases/build.default.workspace-template-app/build.default.workspace-template-app.spec.js
  packages/cli/test/unit/data/schema/config.spec.js
  test/smoke-test.js
  www/pages/about/how-it-works.md
  www/pages/docs/configuration.md
  www/pages/docs/data.md
Labels: CLI, RFC, enhancement

#415 change the project evergreen logo in the header
  www/assets/brand.png
  www/assets/evergreen.svg
  www/components/header/header.css
  www/components/header/header.js
Labels: v0.10.0, website

#414 update docs for strict optimization status
  www/pages/about/how-it-works.md
  www/pages/docs/configuration.md
Labels: documentation, v0.10.0

#409 task/issue 399 resize images for better best practise score
  www/assets/greenwood-logo-1000w.png
  www/assets/greenwood-logo-1500w.png
  www/assets/greenwood-logo-300w.png
  www/assets/greenwood-logo-500w.png
  www/assets/greenwood-logo-750w.png
  www/assets/greenwood-logo-sml.jpg
  www/components/banner/banner.js
Labels: help wanted, website
