Repository ProjectEvergreen/greenwood, pull requests merged in 2020-07, with the labels that each got.

#375 task/issue 372 Add support for ejecting config files including webpack, babel, postcss
  README.md
  packages/cli/src/config/webpack.config.common.js
  packages/cli/src/index.js
  packages/cli/src/lifecycles/context.js
  packages/cli/src/tasks/eject.js
  packages/cli/test/cases/eject.default/eject.default.spec.js
  test/test-bed.js
  www/pages/docs/build.md
Labels: CLI, documentation, enhancement

#378 fix/issue 377 Fix Class Name Conflict With Prism
  packages/cli/src/templates/page-template.js
  www/pages/docs/layouts.md
  www/pages/getting-started/key-concepts.md
  www/styles/home.css
  www/styles/page.css
  www/styles/theme.css
  www/templates/app-template.js
  www/templates/home-template.js
  www/templates/page-template.js
Labels: CLI, bug, documentation, help wanted, website

#379 adjust the link icon styling
  www/styles/page.css
Labels: 0.7.1, website

#381 style headers and link icon to be consistent throughout pages and sizes
  www/styles/page.css
Labels: 0.7.2, website

#383 Bug/issue 371 similar query calls invariant error
  packages/cli/package.json
  packages/cli/src/data/cache.js
  packages/cli/src/data/client.js
  packages/cli/src/data/common.js
  packages/cli/src/lifecycles/serialize.js
  packages/cli/test/cases/build.data.graph-custom-frontmatter/build.data.graph-custom-frontmatter.spec.js
  packages/cli/test/cases/build.data.graph/build.data.graph.spec.js
  packages/cli/test/cases/build.data.graph/src/pages/blog/first-post/index.md
  packages/cli/test/cases/build.data.graph/src/pages/blog/index.md
  packages/cli/test/cases/build.data.graph/src/pages/blog/second-post/index.md
  packages/cli/test/cases/build.data.graph/src/templates/blog-template.js
  packages/cli/test/cases/build.data.graph/src/templates/post-template.js
  packages/cli/test/unit/data/common.spec.js
  yarn.lock
Labels: CLI, Data, P0, bug

#382 task/issue 356 Extendable App Templates
  packages/cli/src/config/webpack.config.common.js
  packages/cli/src/lifecycles/scaffold.js
  packages/cli/src/templates/app-template.js
  packages/cli/src/templates/base-template.js
  packages/cli/src/templates/index.html
  packages/cli/test/cases/build.config.babel/build.config.babel.spec.js
  packages/cli/test/cases/build.default.webpack/webpack.config.common.js
  packages/cli/test/cases/build.default.workspace-template-app/build.default.workspace-template-app.spec.js
  packages/cli/test/cases/build.default.workspace-template-app/src/templates/app-template.js
  test/smoke-test.js
  www/pages/docs/layouts.md
  www/templates/app-template.js
Labels: 0.8.0, CLI, breaking, documentation, enhancement, help wanted

#387 Task/issue 322 remove need for MDIMPORT, rename MYROUTES
  packages/cli/src/lifecycles/scaffold.js
  packages/cli/src/templates/app-template.js
  packages/cli/src/templates/page-template.js
  packages/cli/test/cases/build.config.theme/src/templates/page-template.js
  packages/cli/test/cases/build.data.graph-custom-frontmatter/src/templates/blog-template.js
  packages/cli/test/cases/build.data.graph/src/templates/blog-template.js
  packages/cli/test/cases/build.data.graph/src/templates/page-template.js
  packages/cli/test/cases/build.data.graph/src/templates/post-template.js
  packages/cli/test/cases/build.default.workspace-getting-started/src/templates/blog-template.js
  packages/cli/test/cases/build.default.workspace-getting-started/src/templates/page-template.js
  packages/cli/test/cases/build.default.workspace-template-app/src/templates/app-template.js
  packages/cli/test/cases/build.default.workspace-template-page-style/src/templates/page-template.js
  packages/cli/test/cases/build.default.workspace-template-page/src/templates/page-template.js
  packages/cli/test/cases/build.default.workspace-user-directory-mapping/src/templates/page-template.js
  www/pages/docs/css-and-images.md
  www/pages/docs/layouts.md
  www/pages/getting-started/branding.md
  www/pages/getting-started/creating-content.md
  www/pages/getting-started/key-concepts.md
  www/templates/app-template.js
  www/templates/home-template.js
  www/templates/page-template.js
Labels: CLI, breaking, documentation, enhancement, help wanted

#390 task/issue 389 remove unneeded home template imports, move row/card
  www/pages/index.md
  www/templates/home-template.js
Labels: technical, website

#391 task/issue 341 Add Additional Recommended Puppeteer Dependencies
  .github/workflows/chromium-lib-install.sh
  www/pages/guides/cloudflare-workers-deployment.md
  www/pages/guides/firebase.md
  www/pages/guides/s3-cloudfront.md
Labels: documentation, enhancement, technical

#393 enable link preconnect for google-analytics domain
  packages/plugin-google-analytics/src/index.js
  packages/plugin-google-analytics/test/cases/default/default.spec.js
Labels: Plugins, enhancement

#397 replace MYROUTES in layout docs
  www/pages/docs/layouts.md
Labels: website

#388 filter out index page from children query
  packages/cli/src/data/schema/graph.js
  packages/cli/test/cases/build.data.graph/src/templates/blog-template.js
  packages/cli/test/unit/data/schema/graph.spec.js
Labels: Data, enhancement

#398 task/issue 276 update dependencies
  package.json
  packages/cli/package.json
  yarn.lock
Labels: dependencies

#403 fix typo in layouts docs
  www/pages/docs/layouts.md
Labels: documentation

#402 enhancement/issue 400 switch to internal fonts
  .gitattributes
  www/assets/fonts/SourceSansPro.css
  www/assets/fonts/source-sans-pro-v13-latin-regular.ttf
  www/assets/fonts/source-sans-pro-v13-latin-regular.woff
  www/assets/fonts/source-sans-pro-v13-latin-regular.woff2
  www/components/shelf/shelf.css
  www/styles/theme.css
Labels: help wanted, website
