Repository ProjectEvergreen/greenwood, pull requests merged in 2021-12, with the labels that each got.

#806 fix errant README formatting
  packages/plugin-include-html/README.md
Labels: documentation, Plugins

#808 track missing dependency
  packages/cli/package.json
  packages/plugin-graphql/package.json
Labels: bug, Plugins, CLI

#721 Node 14x minimum version
  .github/workflows/ci-win.yml
  .github/workflows/ci.yml
  packages/cli/package.json
  www/pages/guides/cloudflare-workers-deployment.md
  www/pages/guides/s3-cloudfront.md
Labels: chore, CLI, breaking, alpha.1, v0.20.0

#817 restore support for extending babel configuration
  packages/plugin-babel/README.md
  packages/plugin-babel/src/index.js
  packages/plugin-babel/test/cases/options.extend-config/babel.config.cjs
  packages/plugin-babel/test/cases/options.extend-config/options.extend-config.spec.js
Labels: chore, documentation, Plugins, breaking, alpha.1, v0.20.0

#816 have init lock step initial version to current Greenwood version
  packages/init/src/index.js
  packages/init/src/template/package.json
  packages/init/test/cases/init.default/init.default.spec.js
Labels: feature, Init

#821 favor using latest when documenting npx commands
  www/pages/blog/release/v0-19-0.md
  www/pages/docs/index.md
  www/pages/getting-started/quick-start.md
  www/pages/index.html
Labels: website, documentation, v0.20.0

#822 add a section on scripts and imports to the docs section
  www/pages/docs/css-and-images.md
  www/pages/docs/data.md
  www/pages/docs/layouts.md
  www/pages/docs/menus.md
  www/pages/docs/scripts.md
  www/pages/docs/tech-stack.md
Labels: website, documentation, v0.20.0

#825 release v0.20.0 blog post
  www/pages/blog/index.md
  www/pages/blog/release/v0-20-0.md
Labels: website, content, v0.20.0

#819 better handle `<link>` tag closing variants for inline optimization
  packages/cli/src/config/rollup.config.js
  packages/cli/test/cases/build.config.optimization-inline/build.config-optimization-inline.spec.js
  packages/cli/test/cases/build.config.optimization-inline/src/pages/index.html
  packages/cli/test/cases/build.config.optimization-inline/src/styles/page.css
  packages/cli/test/cases/build.config.optimization-inline/src/templates/app.html
Labels: bug, CLI, v0.20.1

#811 reset PostCSS plugins when optimizing
  packages/plugin-postcss/src/index.js
Labels: chore, Plugins, discussion, v0.20.1

#828 revert Yarn resolution for Lit now that all libs have updated
  package.json
  packages/cli/package.json
  yarn.lock
Labels: chore, CLI

#827 upgrade to ESM gallinago
  package.json
  yarn.lock
Labels: chore

#826 add support and documentation for nvm when contributing
  .github/CONTRIBUTING.md
  .nvmrc
Labels: chore

#834 explicitely add cssnano as a plugin-postcss dep
  packages/plugin-postcss/package.json
Labels: bug, P0, Plugins

#836 point PostCSS to the correct location for resource optimization
  packages/plugin-postcss/src/index.js
Labels: bug, P0, Plugins

#831 fix: remove scrollbar
  www/styles/page.css
Labels: website

#837 missed migrating all website file from CJS to ESM
  www/includes/footer.js
  www/package.json
Labels: chore, website
