Repository ProjectEvergreen/greenwood, pull requests merged in 2021-09, with the labels that each got.

#703 allow for non module script tag bundling
  packages/cli/src/config/rollup.config.js
  packages/cli/test/cases/build.default.workspace-javascript-css/build.default.workspace-javascript-css.spec.js
  packages/cli/test/cases/build.default.workspace-javascript-css/src/pages/index.html
  packages/cli/test/cases/build.default.workspace-javascript-css/src/scripts/non-module.js
  packages/plugin-polyfills/src/index.js
Labels: bug, CLI

#701 update with newer image of presentation starter with decent scaling
  www/assets/greenwood-starter-presentation.png
Labels: website

#711 fix component model docs typos
  www/pages/docs/component-model.md
Labels: website

#713 getting started guide code snippet should be pointing to a footer.js file
  www/pages/getting-started/branding.md
Labels: website

#674 Enhancement/issue 557 resolve node modules using node require resolve
  .github/CONTRIBUTING.md
  packages/cli/src/lib/browser.js
  packages/cli/src/plugins/resource/plugin-node-modules.js
  packages/cli/src/plugins/resource/plugin-standard-html.js
Labels: question, chore, CLI, discussion

#699 upgrade latest puppeteer (includes M1 Mac support)
  packages/cli/package.json
  packages/cli/src/lib/browser.js
  yarn.lock
Labels: chore, P0, alpha.0, SSR, v0.16.0

#723 only use node 14 in github actions
  .github/workflows/ci.yml
  .github/workflows/master.yml
  .github/workflows/release.yml
  netlify.toml
Labels: chore, CLI, alpha.1, v0.16.0

#722 better handle the duality of @greenwood node modules resolution
  packages/cli/src/plugins/resource/plugin-node-modules.js
  packages/cli/test/cases/develop.default/develop.default.spec.js
  packages/plugin-graphql/test/cases/develop.default/develop.default.spec.js
Labels: bug, P0, CLI, alpha.1, v0.16.0

#727 show a plugin example we actually support
  www/pages/docs/css-and-images.md
Labels: documentation

#724 clean up test case
  packages/cli/test/cases/theme-pack/theme-pack.build.spec.js
Labels: chore, CLI

#716 handle missed cases for files in exports maps and transient dependency imports
  packages/cli/package.json
  packages/cli/src/plugins/resource/plugin-node-modules.js
  packages/cli/test/cases/develop.default/develop.default.spec.js
  packages/cli/test/cases/develop.default/package.json
  yarn.lock
Labels: bug, CLI

#733 handle require.resolve fallback when walking node_modules with no main field in package.json
  packages/cli/package.json
  packages/cli/src/lib/node-modules-utils.js
  packages/cli/src/plugins/resource/plugin-node-modules.js
  packages/cli/test/cases/develop.default/develop.default.spec.js
  packages/cli/test/cases/develop.default/package.json
  packages/plugin-polyfills/src/index.js
  yarn.lock
Labels: bug, P0, CLI, alpha.3, v0.16.0

#735 fix scrollbar issues, small styling adjustments
  www/components/shelf/shelf.css
  www/components/shelf/shelf.js
  www/styles/home.css
  www/styles/page.css
Labels: website

#731 link the version in the footer to GitHub releases
  www/components/footer/footer.js
Labels: website

#730 make github actions configuration more consistent
  .github/workflows/ci-win.yml
  .github/workflows/ci.yml
  .github/workflows/master.yml
  README.md
  packages/cli/test/cases/develop.default/develop.default.spec.js
  packages/cli/test/cases/develop.plugins.context/develop.plugins.context.spec.js
  packages/cli/test/cases/serve.default/serve.default.spec.js
  packages/cli/test/cases/theme-pack/theme-pack.develop.spec.js
  packages/plugin-graphql/test/cases/develop.default/develop.default.spec.js
  packages/plugin-graphql/test/cases/qraphql-server/graphql-server.spec.js
  packages/plugin-import-css/test/cases/develop.default/develop.default.spec.js
  packages/plugin-import-json/test/cases/develop.default/develop.default.spec.js
  packages/plugin-typescript/test/cases/develop.default/develop.default.spec.js
Labels: chore, P0, discussion
