Repository ProjectEvergreen/greenwood, pull requests merged in 2023-05, with the labels that each got.

#1094 Website/new greenwood logo
  www/assets/greenwood-logo-1000w.png
  www/assets/greenwood-logo-1000w.webp
  www/assets/greenwood-logo-1500w.png
  www/assets/greenwood-logo-1500w.webp
  www/assets/greenwood-logo-300w.png
  www/assets/greenwood-logo-300w.webp
  www/assets/greenwood-logo-500w.png
  www/assets/greenwood-logo-500w.webp
  www/assets/greenwood-logo-750w.png
  www/assets/greenwood-logo-750w.webp
  www/assets/greenwood-logo-og.png
  www/assets/greenwood-logo-sml.jpg
  www/components/banner/banner.css
  www/components/banner/banner.js
  www/favicon.ico
  www/templates/app.html
Labels: website

#1095 Content/state of greenwood 2023 blog post
  www/pages/blog/index.md
  www/pages/blog/state-of-greenwood-2023.md
Labels: content

#1100 bug/include resource tracking and serialization for all pages
  packages/cli/src/commands/build.js
  packages/cli/src/lib/resource-utils.js
  packages/cli/src/lifecycles/bundle.js
  packages/cli/src/lifecycles/compile.js
  packages/cli/src/lifecycles/graph.js
  packages/cli/src/lifecycles/prerender.js
  packages/cli/src/plugins/copy/plugin-copy-graph-json.js
  packages/cli/src/plugins/resource/plugin-standard-html.js
  packages/cli/test/cases/build.default.ssr-static-export/build.default.ssr-static-export.spec.js
  packages/cli/test/cases/develop.ssr/develop.ssr.spec.js
  packages/cli/test/cases/serve.default.ssr/serve.default.ssr.spec.js
  packages/cli/test/cases/serve.default.ssr/src/components/header.js
  packages/cli/test/cases/serve.default.ssr/src/templates/app.html
Labels: bug, P0, CLI, SSR

#1103 Bug/issue 1102 not found static assets returning 500 for serve command
  packages/cli/src/lifecycles/serve.js
  packages/cli/test/cases/serve.default.api/serve.default.api.spec.js
  packages/cli/test/cases/serve.default.ssr/serve.default.ssr.spec.js
  packages/cli/test/cases/serve.default/serve.default.spec.js
Labels: bug, CLI

#1105 bug/use Worker threads for full API routes cache busting in development mode
  packages/cli/src/lib/api-route-worker.js
  packages/cli/src/plugins/resource/plugin-api-routes.js
Labels: bug, P0, CLI, SSR

#1113 bug/issue 1112 upgrade apollo/client and update entry point specifier path
  packages/plugin-graphql/package.json
  packages/plugin-graphql/src/core/cache.js
  yarn.lock
Labels: bug, Plugins, Data

#1111 clarify usage of `new URL` with directories in docs
  www/pages/docs/configuration.md
  www/pages/guides/theme-packs.md
Labels: documentation
