Repository ProjectEvergreen/greenwood, pull requests merged in 2023-11, with the labels that each got.

#1107 add support for optimizing CSS `:has` / `:is` pseudo-selectors
  packages/cli/src/plugins/resource/plugin-standard-css.js
  packages/cli/test/cases/build.config.optimization-default/fixtures/expected.css
  packages/cli/test/cases/build.config.optimization-default/src/styles/main.css
Labels: CLI, feature

#1179 website/fix missing docs shelf navigation
  www/templates/page.html
Labels: bug, website

#1180 bug/ensure resolving graph.json respects base path configuration
  packages/cli/src/plugins/resource/plugin-standard-json.js
  packages/cli/test/cases/develop.config.base-path/develop.config.base-path.spec.js
  packages/cli/test/cases/develop.default/develop.default.spec.js
  packages/cli/test/cases/serve.config.base-path/serve.config.base-path.spec.js
  packages/cli/test/cases/serve.default/serve.default.spec.js
Labels: bug, CLI, Data, v0.29.0

#1172 chore/Issue 1016: Replace the use of request with fetch in test cases
  packages/cli/test/cases/develop.default.hud-disabled/develop.default.hud-disabled.spec.js
  packages/cli/test/cases/develop.default.hud/develop.default.hud.spec.js
  packages/cli/test/cases/develop.default/develop.default.spec.js
  packages/cli/test/cases/develop.default/src/api/submit-json.js
  packages/cli/test/cases/develop.plugins.context/develop.plugins.context.spec.js
  packages/cli/test/cases/develop.spa/develop.spa.spec.js
  packages/cli/test/cases/develop.ssr/develop.ssr.spec.js
  packages/cli/test/cases/serve.config.static-router/serve.config.static-router.spec.js
  packages/cli/test/cases/serve.default.api/serve.default.api.spec.js
  packages/cli/test/cases/serve.default.ssr-prerender-api-hybrid/serve.default.ssr-prerender-api-hybrid.spec.js
  packages/cli/test/cases/serve.default.ssr-prerender/serve.default.ssr-prerender.spec.js
  packages/cli/test/cases/serve.default.ssr-static-export/serve.default.ssr-static-export.spec.js
  packages/cli/test/cases/serve.default.ssr/serve.default.ssr.spec.js
  packages/cli/test/cases/serve.default/serve.default.spec.js
  packages/cli/test/cases/serve.spa/serve.spa.spec.js
  packages/cli/test/cases/theme-pack/theme-pack.develop.spec.js
  packages/init/test/cases/develop.default/develop.default.spec.js
  packages/plugin-adapter-netlify/test/cases/build.default/build.default.spec.js
  packages/plugin-adapter-vercel/test/cases/build.default/build.default.spec.js
  packages/plugin-graphql/test/cases/develop.default/develop.default.spec.js
  packages/plugin-graphql/test/cases/qraphql-server/graphql-server.spec.js
  packages/plugin-import-css/test/cases/develop.default/develop.default.spec.js
  packages/plugin-import-css/test/cases/exp-serve.ssr/exp-serve.ssr.spec.js
  packages/plugin-import-json/test/cases/develop.default/develop.default.spec.js
  packages/plugin-import-json/test/cases/exp-serve.ssr/exp-serve.ssr.spec.js
  packages/plugin-renderer-lit/test/cases/serve.default/serve.default.spec.js
  packages/plugin-typescript/test/cases/develop.default/develop.default.spec.js
  packages/plugin-typescript/test/cases/exp-prerender.serve.ssr/exp-prerender.serve.ssr.spec.js
  packages/plugin-typescript/test/cases/exp-serve.ssr/exp-serve.ssr.spec.js
Labels: chore

#1174 content/v0.29.0 release blog post
  www/assets/serverless.webp
  www/pages/blog/index.md
  www/pages/blog/release/v0-29-0.md
  www/pages/docs/css-and-images.md
Labels: documentation, content, v0.29.0
