Repository ProjectEvergreen/greenwood, pull requests merged in 2023-03, with the labels that each got.

#1061 correctly order Apollo data `<script>` tag inside `<head>` tag
  packages/plugin-graphql/src/index.js
  packages/plugin-graphql/test/cases/query-children/query-children.spec.js
  packages/plugin-graphql/test/cases/query-config/query-config.spec.js
  packages/plugin-graphql/test/cases/query-custom-frontmatter/query-custom-frontmatter.spec.js
  packages/plugin-graphql/test/cases/query-custom-schema/query-custom-schema.spec.js
  packages/plugin-graphql/test/cases/query-graph/query-graph.spec.js
  packages/plugin-graphql/test/cases/query-menu/query-menu.spec.js
Labels: enhancement, Plugins, Data

#1076 refactor copy lifecycle to use leverage fs.copyFile instead of streams
  packages/cli/src/lifecycles/copy.js
  packages/cli/test/cases/develop.default/develop.default.spec.js
Labels: enhancement, CLI, alpha.4

#1071 upgrade actions/setup-node to v3 for node 18
  .github/workflows/ci-exp.yml
  .github/workflows/ci-win-exp.yml
  .github/workflows/ci-win.yml
  .github/workflows/ci.yml
  .github/workflows/master.yml
  .github/workflows/release.yml
  www/pages/guides/github-pages.md
Labels: chore, website, documentation

#1077 update repository and homepage fields for all package jsons
  packages/cli/package.json
  packages/init/package.json
  packages/plugin-babel/package.json
  packages/plugin-google-analytics/package.json
  packages/plugin-graphql/package.json
  packages/plugin-import-commonjs/package.json
  packages/plugin-import-css/package.json
  packages/plugin-import-json/package.json
  packages/plugin-include-html/package.json
  packages/plugin-polyfills/package.json
  packages/plugin-postcss/package.json
  packages/plugin-renderer-lit/package.json
  packages/plugin-renderer-puppeteer/package.json
  packages/plugin-typescript/package.json
Labels: chore, alpha.4, v0.28.0

#1066 Enhancement/restore rollup local workspace resolution
  packages/cli/src/config/rollup.config.js
  packages/plugin-graphql/README.md
  packages/plugin-graphql/test/cases/query-custom-schema/src/pages/index.html
Labels: enhancement, documentation, CLI, Data, breaking, alpha.4, v0.28.0
